### ISSUE TITLE
Missing line-feed after moniker in CLI invocation

### ISSUE THREAD

**Issue by atifaziz** [alexmg/Moniker#1]
## Steps to Reproduce

Install moniker:

```
PS> dotnet tool install -g Moniker.Cli
You can invoke the tool using the following command: moniker
Tool 'moniker.cli' (version '1.0.0') was successfully installed.
```

Sample 5 monikers:

```
PS> 1..5 | % { moniker }
```

## Expected Results

Expected 5 monikers, each listed on its own line, as in:

```
historical-penguin
wobbling-unicorn
brazen-sheep
bailing-joey
knotted-pika
```

## Actual Results

Instead they appeared concatenated together on a single line like so:

```
historical-penguinwobbling-unicornbrazen-sheepbailing-joeyknotted-pika
```

**Comment by alexmg** [comment]
I’m sorry for the delayed response. I recently took some time to review old projects and noticed this issue. I understand it may no longer be relevant due to the time that has passed, but I wanted to let you know that the issue has been resolved, and updated versions of the packages have been published to NuGet.
