### ISSUE TITLE
please update the global tool to latest .NET Core 

### ISSUE THREAD

**Issue by ignatandrei** [alexmg/Moniker#6]
I try to use in a .NET Core 3.1 docker container

FROM mcr.microsoft.com/dotnet/core/sdk:3.1

and the error is 

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=debian.10-x64

**Comment by ignatandrei** [comment]
?

**Comment by alexmg** [comment]
I’m sorry for the delayed response. I recently took some time to review old projects and noticed this issue. I understand it may no longer be relevant due to the time that has passed, but I wanted to let you know that the issue has been resolved, and updated versions of the packages have been published to NuGet.

**Comment by ignatandrei** [comment]
Thank you. It is indeed worthy to do it ! I will verify ASAP!
